### ISSUE TITLE
.

### ISSUE THREAD

**Issue by IPav7** [pavelkeyzik/sai-system-front#1]

**Comment by pavelkeyzik** [comment]
аххах Что?) Ты даже запустить не смог 😄

**Comment by IPav7** [comment]
РАЗРАБОТЧИК ПИТУХ! БУДЕШЬ НОВЫЙ КОМП ПОКУПАТЬ

**Comment by pavelkeyzik** [comment]
Обращайся в Facebook! Это create-react-app сгенерировал и я лишнее удалил.
Как ты запускал?
